# Generated by Django 5.0.6 on 2024-12-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=228)),
            ],
        ),
    ]
