# Generated by Django 5.1.4 on 2024-12-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
