# Generated by Django 5.1.4 on 2024-12-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Museos', '0002_alter_museo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Museos.museo')),
            ],
        ),
    ]
